#!/bin/bash

LOCK=/usr/share/i3lock-fancy/lock.png
RES=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
IMAGE=$(mktemp).png

ffmpeg -probesize 100M -thread_queue_size 32 -f x11grab -video_size $RES \
     -y -i $DISPLAY -i $LOCK -i $LOCK -filter_complex \
     "eq=gamma=0.75,boxblur=7:2,overlay=(main_w-overlay_w)/4:(main_h-overlay_h)/2,overlay=3*(main_w-overlay_w)/4:(main_h-overlay_h)/2" \
     -vframes 1 $IMAGE

i3lock -n -i "$IMAGE"
