format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$aws\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

[character]
success_symbol = "[❯](bright-purple)"
error_symbol = "[❯](bold red)"

[git_branch]
format = "[$branch](purple) "

[directory]
truncation_symbol = "…/"
truncation_length = 0
truncate_to_repo = false

[cmd_duration]
min_time = 5_000
format = "[$duration]($style)"
